downgrade micrometer to fix IllegalArgumentException after bump of spring boot
error: j.l.IllegalArgumentException: Counts in ClassicHistogramBuckets cannot be negative.

refs: https://github.com/micrometer-metrics/micrometer/issues/5193